### ISSUE TITLE
validation_report: pq_data

### ISSUE THREAD

**Issue by sachinstl** [microsoft/vivainsights#11]
For validation report: While using pq_data under validation_report in vivainsights error is, 

Error in `rename()`:
! Can't rename columns that don't exist.
✖ Column `Instant_Message_hours` doesn't exist.

Kindly assist for sample data to use validation_report in vivainsights. Thanks

**Comment by martinctc** [comment]
Thanks for flagging this @sachinstl - addressing this in the patch release in #12.
